# Generated by Django 5.1.6 on 2025-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
