# Generated by Django 5.1.6 on 2025-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="company_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="tax_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
