# Generated by Django 5.1.6 on 2025-03-06 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_verified_vendorprofile_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 6, 17, 57, 26, 82834, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
