# Generated by Django 5.1.6 on 2025-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="profile_completion",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="submission_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("submitted", "Submitted")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="tax_id",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
